# Site settings
title: Gina Liao
email: gina@ginaliao.com
description: > # this means to ignore newlines until "baseurl:"
  A self-taught front-end developer with a fancy degree in graphic design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.ginaliao.com" # the base hostname & protocol for your site
twitter_username: itsginarrr
linkedin_username: ginaliao
github_username:  ginaliao
source: ./src
destination: ./dist
permalink: /blog/:title/
jekyll-archives:
  enabled: [categories]
  layout: 'archive'
collections:
  work:
    output: true
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
      
# Build settings
plugins:
  - jekyll-archives
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
exclude: ['js', 'scss']
keep_files: ['js', 'css']